import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {newRoom,addPlayer,makeKit,advanceRoom,applyInput,hurt,roomSnapshot,solidBoxes,segmentBox,predictPlayer,RESPAWN_MS} from '../public/arena-core.js';
import {creationStats,WEAPONS} from '../public/combat.js';
import {WORLD_ENTITIES,RING_RADIUS} from '../public/world-data.js';
import {RINGS} from '../public/rules.js';
import {SUPPLY_BLUEPRINTS,SUPPORT_DROPS} from '../public/supply-catalog.js';
import {validateBlueprint} from '../public/blueprint.js';
import {blueprintMetrics} from '../public/blueprint-metrics.js';
import {createGeneratedModel} from '../public/generated-model.js';
import {arenaStore} from '../worker/arena-store.js';
import {handleArenaAPI} from '../worker/arena-api.js';
let count=0;const check=async(name,fn)=>{await fn();console.log('PASS '+name);count++;};
const sample=JSON.parse(fs.readFileSync(new URL('../validation/live/dragon.json',import.meta.url))).blueprint;
const dragon=validateBlueprint({...sample,version:3,traits:{weapon:'flame',armor:'heavy',mass:'heavy',emitter:[0,2,4]}});
function clearWorld(r,keep=[]){for(const e of WORLD_ENTITIES)if(!keep.includes(e.id))r.destroyed[e.id]=1e12;}
function room(keep=[]){const r=newRoom(100000),p=addPlayer(r,'a','Alpha');p.protectedUntil=0;clearWorld(r,keep);return [r,p];}
function run(r,ms,inputs={}){for(let t=0;t<ms;t+=1000/30){for(const p of Object.values(r.players)){p.lastSeen=r.time;applyInput(r,p.id,{seq:p.lastSeq+1,input:inputs[p.id]||{}},r.time);}advanceRoom(r,r.time+Math.min(1000/30,ms-t));}}
await check('weapon and armor choices have bounded, distinct tradeoffs',()=>{const auto=creationStats({...dragon,movement:'carry',traits:{...dragon.traits,weapon:'automatic'}}),bow=creationStats('bow'),shield=creationStats({...dragon,movement:'carry',traits:{...dragon.traits,weapon:'none',armor:'shield'}});assert.ok(auto.interval<bow.interval&&auto.offense>bow.offense&&auto.speed<bow.speed);assert.equal(auto.projectileSpeed,68);assert.equal(shield.weapon,'punch');assert.ok(shield.armor>.4&&shield.mountMax===90);for(const weapon of Object.keys(WEAPONS)){const s=creationStats({...dragon,traits:{...dragon.traits,weapon}});assert.ok(s.damage<=55&&s.speed<=32&&s.mountMax<=250);}});
await check('punches wind up, hit once, miss at range, and retries cannot repeat damage',()=>{
 const [r,p]=room(),q=addPlayer(r,'b','Rival');Object.assign(p,{x:0,z:0,yaw:0});Object.assign(q,{x:0,z:1.8,protectedUntil:0});
 const packet={seq:1,input:{cameraYaw:0},command:{id:1,type:'fire'}};applyInput(r,'a',packet,r.time);assert.equal(p.kit.stats.weapon,'punch');assert.equal(q.health,100);assert.equal(r.projectiles.length,0);
 run(r,100);assert.equal(q.health,100);run(r,80);const health=q.health;assert.ok(health<100);const before={x:q.x,y:q.y,z:q.z};
 applyInput(r,'a',packet,r.time);run(r,240);assert.equal(q.health,health);assert.equal(r.events.filter(e=>e.type==='hit').length,1);for(const k of ['x','y','z'])assert.equal(q[k],before[k]);
 q.z=4;run(r,700,{a:{fire:true,cameraYaw:0}});assert.equal(q.health,health);assert.ok(r.events.filter(e=>e.type==='swing').length>=2);
});
await check('punches follow the current body facing at every angle even when the camera faces away',()=>{
 for(const yaw of [0,Math.PI/2,Math.PI,-Math.PI/2,.73]){const [r,p]=room(),front=addPlayer(r,'front','Front'),back=addPlayer(r,'back','Back');Object.assign(p,{x:0,z:0,yaw});
  Object.assign(front,{x:Math.sin(yaw)*1.7,z:Math.cos(yaw)*1.7,protectedUntil:0});Object.assign(back,{x:-Math.sin(yaw)*1.7,z:-Math.cos(yaw)*1.7,protectedUntil:0});
  applyInput(r,p.id,{seq:1,input:{cameraYaw:yaw+Math.PI},command:{id:1,type:'fire'}},r.time);assert.equal(r.events.find(e=>e.type==='swing').yaw,yaw);run(r,200);assert.equal(front.health,83.8);assert.equal(back.health,100);assert.equal(p.yaw,yaw);
 }
});
await check('projectile contact produces one confirmed hit event at its contact point',()=>{
 const [r,p]=room(),q=addPlayer(r,'b','Rival');Object.assign(p,{kit:makeKit('bow'),x:0,z:0,yaw:0});Object.assign(q,{x:0,z:5,protectedUntil:0});applyInput(r,'a',{seq:1,input:{cameraYaw:0},command:{id:1,type:'fire'}},r.time);run(r,400);assert.equal(r.events.filter(e=>e.type==='hit').length,1);assert.equal(r.events.filter(e=>e.type==='impact').length,0);const hit=r.events.find(e=>e.type==='hit');assert.ok(hit.z>4&&hit.z<5);assert.equal(typeof hit.attack,'number');
});
await check('server geometry bounds match renderer and muzzle stays on creation',()=>{for(const kind of ['dragon','octopus','teapot']){const b=JSON.parse(fs.readFileSync(new URL('../validation/live/'+kind+'.json',import.meta.url))).blueprint,model=createGeneratedModel(b),metrics=blueprintMetrics(b);metrics.size.forEach((v,i)=>assert.ok(Math.abs(v-model.size.toArray()[i])<1e-6));model.dispose();}const tiny={...dragon,joints:[],parts:Array.from({length:32},()=>({shape:'box',position:[0,0,0],size:[.025,.025,.025],rotation:[0,0,0],joint:-1,color:0,studs:false}))};assert.throws(()=>validateBlueprint(tiny));const small={...tiny,parts:tiny.parts.map(p=>({...p,size:[.11,.11,.11]})),traits:{...dragon.traits,emitter:[16,16,16]}};const kit=makeKit('test',validateBlueprint(small));assert.ok(kit.muzzle.every(v=>Math.abs(v)<4));});
await check('40 players share a room and snapshots expose no input/session secrets',()=>{const r=newRoom(1e5);for(let i=0;i<40;i++)addPlayer(r,'p'+i,'Builder '+i);const s=roomSnapshot(r,'p0');assert.equal(s.players.length,40);assert.ok(s.players.every(p=>!('input'in p)&&!('lastSeen'in p)));});
await check('fast vehicles stop at houses without impacts, damage or relocation',()=>{
 for(const mode of ['car','plane']){
  const [r,p]=room(['house:0']),[empty,q]=room();
  for(const player of [p,q])Object.assign(player,{kit:makeKit(mode),mountHealth:120,x:-35,z:-16,y:1,flightAltitude:1,yaw:Math.PI/2,speed:29});
  run(r,1400,{a:{z:1,cameraYaw:Math.PI/2}});run(empty,1400,{a:{z:1,cameraYaw:Math.PI/2}});
  for(const key of ['y','z','yaw','health','mountHealth'])assert.equal(p[key],q[key],mode+' '+key);assert.ok(p.x< -20);assert.ok(q.x> -12);assert.ok(p.speed<.01);
  assert.equal(p.kit.id,mode);assert.ok(!r.destroyed['house:0']);assert.ok(!r.events.some(e=>['crash','collision','break'].includes(e.type)));
 }
});
await check('heavy mounts stop at trees and safe ground landings do not eject pilots',()=>{
 const [r,p]=room(['tree:inner:0']),tree=WORLD_ENTITIES.find(e=>e.id==='tree:inner:0').boxes[0];
 Object.assign(p,{kit:makeKit('heavy',{...dragon,movement:'drive',traits:{...dragon.traits,weapon:'none'}}),mountHealth:200,x:tree.x,z:tree.z-12,yaw:0,speed:24});
 run(r,1500,{a:{z:1,cameraYaw:0}});assert.ok(p.z<tree.z-1);assert.ok(!r.destroyed['tree:inner:0']);assert.equal(p.mountHealth,200);
 Object.assign(p,{kit:makeKit('plane'),mountHealth:120,y:.2,vertical:-10,flightAltitude:0,speed:0});run(r,200);assert.equal(p.y,.2);run(r,200,{a:{down:true}});assert.equal(p.y,0);assert.equal(p.kit.id,'plane');assert.equal(p.health,100);
});
await check('all five flight markers admit a correctly aligned plane',()=>{assert.ok(RING_RADIUS>4);for(let i=0;i<RINGS.length;i++){const [r,p]=room(['ring:'+i]),ring=RINGS[i],next=RINGS[(i+1)%RINGS.length],yaw=Math.atan2(next.x-ring.x,next.z-ring.z);Object.assign(p,{kit:makeKit('plane'),mountHealth:120,x:ring.x-Math.sin(yaw)*10,z:ring.z-Math.cos(yaw)*10,y:ring.y-1.375,flightAltitude:ring.y-1.375,yaw,speed:29});run(r,1300,{a:{z:1,cameraYaw:yaw}});assert.equal(p.kit.id,'plane','ring '+i);}});
await check('mounts cannot jump; prediction cannot damage or change a loadout',()=>{const [r,p]=room(['house:0']);Object.assign(p,{kit:makeKit('car'),mountHealth:155,x:0,z:0});run(r,34,{a:{jump:true}});assert.equal(p.y,0);Object.assign(p,{kit:makeKit('plane'),mountHealth:120,x:-25,z:-16,y:1,flightAltitude:1,yaw:Math.PI/2,speed:32});const before=p.health;for(let i=0;i<30;i++)predictPlayer(p,{z:1,cameraYaw:Math.PI/2},1/30,{...r,preview:true});assert.equal(p.kit.id,'plane');assert.equal(p.health,before);assert.equal(p.mountHealth,120);});
await check('cover restoration waits for occupants without moving them; time is monotonic',()=>{const [r,p]=room();p.x=-17;p.z=-16;r.destroyed['house:0']=r.time+1;run(r,34);assert.equal(p.x,-17);assert.equal(p.z,-16);assert.equal(p.health,100);assert.ok(r.destroyed['house:0']>r.time);p.x=0;p.z=0;run(r,1100);assert.equal(r.destroyed['house:0'],undefined);const t=r.time;advanceRoom(r,t-500);assert.equal(r.time,t);});
await check('moving assembly completes a custom mount with shield and trusted flame',()=>{const [r,p]=room();p.x=0;p.z=0;applyInput(r,p.id,{seq:1,input:{z:1},command:{id:1,type:'build'}},r.time,makeKit('dragon',dragon));run(r,1000,{a:{z:1}});assert.ok(p.building);assert.ok(p.z>5);run(r,400,{a:{z:1}});assert.equal(p.kit.id,'dragon');assert.equal(p.kit.stats.weapon,'flame');assert.ok(p.mountHealth>100);run(r,800,{a:{z:1,up:true,fire:true}});assert.ok(p.y>0);assert.ok(r.events.some(e=>e.type==='shot'&&e.weapon==='flame'));});
await check('mount health absorbs damage, then the pilot is exposed; one death counts once',()=>{const [r,p]=room(),b=addPlayer(r,'b','Beta'),c=addPlayer(r,'c','Gamma');b.protectedUntil=c.protectedUntil=0;b.kit=makeKit('dragon',dragon);b.mountHealth=b.kit.stats.mountMax;hurt(r,b,50,p.id);assert.equal(b.health,100);assert.ok(b.mountHealth<b.kit.stats.mountMax);hurt(r,b,2000,p.id);hurt(r,b,2000,p.id);assert.equal(b.health,0);assert.equal(b.kit.id,'foot');assert.equal(p.kills,1);assert.equal(b.deaths,1);assert.equal(c.kills,0);assert.equal(b.respawnAt-r.time,RESPAWN_MS);run(r,11900);assert.equal(b.health,0);run(r,150);assert.equal(b.health,100);assert.equal(b.kit.id,'foot');assert.ok(b.protectedUntil>r.time);});
await check('bow reaches distant rivals, projectiles respect cover, melee has no projectile',()=>{const [r,p]=room(),b=addPlayer(r,'b','Beta');Object.assign(p,{kit:makeKit('bow'),x:0,z:0,yaw:0});Object.assign(b,{x:0,z:40,protectedUntil:0});applyInput(r,p.id,{seq:1,input:{cameraYaw:0},command:{id:1,type:'fire'}},r.time);run(r,1300);assert.ok(b.health<100);const [r2,q]=room(['house:0']),v=addPlayer(r2,'b','Beta');Object.assign(q,{kit:makeKit('bow'),x:-17,z:-25,yaw:0});Object.assign(v,{x:-17,z:-6,protectedUntil:0});run(r2,1500,{a:{fire:true,cameraYaw:0}});assert.equal(v.health,100);q.kit=makeKit('sword');q.x=0;q.z=0;v.x=0;v.z=2;q.nextShot=0;applyInput(r2,q.id,{seq:q.lastSeq+1,input:{cameraYaw:0},command:{id:1,type:'fire'}},r2.time);run(r2,220);assert.ok(v.health<100);assert.ok(r2.events.some(e=>e.type==='swing'));});
await check('melee uses height, facing and line of sight, including placed scenery',()=>{const [r,p]=room(['crate:0','crate:2']);Object.assign(p,{kit:makeKit('sword'),x:-13,z:12,y:20,yaw:0});applyInput(r,p.id,{seq:1,input:{cameraYaw:0},command:{id:1,type:'fire'}},r.time);assert.equal(Object.keys(r.damage).length,0);p.x=0;p.z=0;p.y=0;p.nextShot=0;r.placed.push({id:'placed:test',x:0,z:2,w:1,h:2,d:1,hp:30,color:'#ffffff'});applyInput(r,p.id,{seq:2,input:{cameraYaw:0},command:{id:2,type:'fire'}},r.time);run(r,220);assert.ok(r.destroyed['placed:test']);});
await check('automatic fire overheats and stale inputs stop firing and movement',()=>{const [r,p]=room();p.kit=makeKit('gun',{...dragon,movement:'carry',traits:{...dragon.traits,weapon:'automatic'}});run(r,2400,{a:{fire:true}});assert.ok(r.events.filter(e=>e.type==='shot').length>5);assert.ok(p.overheatedUntil>r.time);p.kit=makeKit();p.input={z:1,fire:true};p.inputAt=r.time-1000;const shots=r.events.filter(e=>e.type==='shot').length;advanceRoom(r,r.time+500);assert.equal(r.events.filter(e=>e.type==='shot').length,shots);assert.equal(p.speed,0);});
await check('one player claims each landed pickup; buffs last ten seconds',()=>{const [r,p]=room(),b=addPlayer(r,'b','Beta');p.x=b.x=0;p.z=b.z=0;p.health=35;for(const type of ['health','defense','speed'])r.drops.push({id:type,type,x:0,z:0,born:r.time-6000,lands:r.time-500,expires:r.time+1000});run(r,34);assert.equal(r.drops.length,3);for(const mode of ['health','defense','speed'])applyInput(r,p.id,{seq:p.lastSeq+1,command:{id:p.lastCommand+1,type:'pickup',mode}},r.time);assert.equal(r.drops.length,0);assert.equal(p.health,100);assert.ok(p.defenseUntil-r.time>9900&&p.speedUntil-r.time>9900);assert.equal(b.defenseUntil,0);const timer=p.speedUntil;run(r,10050);assert.ok(r.time>timer);});
await check('sky drops cycle health, defense and speed without any equipment',()=>{
 const [r,p]=room();Object.assign(p,{x:40,z:40});const types=[];
 for(let i=0;i<12;i++){r.nextDrop=r.time;run(r,34);const d=r.drops.at(-1);types.push(d.type);assert.equal(d.lands-d.born,5500);assert.ok(!('equipment' in d));assert.ok(r.drops.length<=6);}
 assert.deepEqual(types,Array.from({length:12},(_,i)=>SUPPORT_DROPS[i%3]));r.nextDrop=r.time+1e6;run(r,46000);assert.equal(r.drops.length,0);
});
await check('support pickups retain effects and never replace a creation; legacy gear is removed',()=>{
 for(const type of SUPPORT_DROPS){const [r,p]=room();Object.assign(p,{x:0,z:0,health:40,kit:makeKit('bow')});r.nextDrop=r.time+1e6;
 r.drops.push({id:type,type,x:0,z:0,born:r.time-6000,lands:r.time-500,expires:r.time+10000});run(r,34);assert.equal(r.drops.length,1);applyInput(r,p.id,{seq:p.lastSeq+1,command:{id:p.lastCommand+1,type:'pickup',mode:type}},r.time);assert.equal(p.kit.id,'bow');assert.equal(r.drops.length,0);
 if(type==='health')assert.equal(p.health,100);if(type==='speed')assert.ok(p.speedUntil>r.time+9000);if(type==='defense'){assert.ok(p.defenseUntil>r.time+9000);hurt(r,p,20,'other');assert.equal(p.health,31.9);}}
 const [r,p]=room();Object.assign(p,{x:0,z:0});r.nextDrop=r.time+1e6;r.drops.push({id:'legacy',type:'equipment',equipment:'supply:rover',x:0,z:0,lands:0,expires:r.time+10000});run(r,34);assert.equal(r.drops.length,0);assert.equal(p.kit.id,'foot');
});
await check('weapons and vehicles remain buildable with no equipment lifetime',()=>{
 for(const id of ['sword','bow','supply:rover']){const [r,p]=room();Object.assign(p,{x:0,z:0});const kit=makeKit(id,SUPPLY_BLUEPRINTS.get(id)||null);applyInput(r,p.id,{seq:1,command:{id:1,type:'build'}},r.time,kit);run(r,1300);assert.equal(p.kit.id,id);run(r,65000);assert.equal(p.kit.id,id);assert.ok(p.kit.stats.damage>0);}
});
await check('generated scenery is placed once with shared bounded shot cover',()=>{const [r,p]=room();p.x=0;p.z=0;const b={...dragon,movement:'static',ability:'none',traits:{...dragon.traits,weapon:'none'}};applyInput(r,p.id,{seq:1,command:{id:1,type:'build'}},r.time,makeKit('statue',b));run(r,2900);assert.equal(r.placed.length,1);assert.equal(p.kit.id,'foot');assert.ok(solidBoxes(r).some(e=>e.entity.id===r.placed[0].id));applyInput(r,p.id,{seq:2,command:{id:1,type:'build'}},r.time,makeKit('statue',b));run(r,3000);assert.equal(r.placed.length,1);});
// SQLite executes the actual generated migrations and SQL, with async scheduling
// to exercise competing D1-style requests. This is not a network performance test.
const sqlite=new DatabaseSync(':memory:');for(const name of fs.readdirSync(new URL('../drizzle',import.meta.url)).filter(n=>n.endsWith('.sql')).sort())sqlite.exec(fs.readFileSync(new URL('../drizzle/'+name,import.meta.url),'utf8'));
const DB={prepare(sql){return {bind(...args){return {async first(){await Promise.resolve();return sqlite.prepare(sql).get(...args)||null;},async run(){await Promise.resolve();const r=sqlite.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}};}};}};}};
const api=async(path,body={},principal='owner',extra={})=>handleArenaAPI(new Request('https://brickwild.test/api/arena/'+path,{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://brickwild.test',...(principal?{'oai-authenticated-user-id':principal}:{}),...extra},body:JSON.stringify({mapVersion:1,...body})}),{DB});
await check('SQLite compare-and-swap preserves simultaneous room joins and monotonic revisions',async()=>{const store=arenaStore(DB),results=await Promise.all(Array.from({length:6},(_,i)=>store.mutate('CAS1',(r,t)=>addPlayer(r,'cas'+i,'Concurrent '+i,t))));const row=sqlite.prepare('SELECT * FROM arena_rooms WHERE id = ?').get('CAS1'),r=JSON.parse(row.snapshot);assert.equal(Object.keys(r.players).length,6);assert.equal(row.revision,6);assert.equal(new Set(results.map(r=>r.room.revision)).size,6);});
let a,b,c;
await check('three authenticated HTTP clients see the same room and bound identity',async()=>{const response=await api('join',{name:'Alpha',room:'HTTP',avatarColor:'#579fe2'},'u1');assert.equal(response.status,200);a=await response.json();assert.equal(a.snapshot.players.find(p=>p.id===a.snapshot.self).avatarColor,'#579fe2');b=await (await api('join',{name:'Beta',room:'HTTP',avatarColor:'bad-color'},'u2')).json();assert.equal(b.snapshot.players.find(p=>p.id===a.snapshot.self).avatarColor,'#579fe2');assert.equal(b.snapshot.players.find(p=>p.id===b.snapshot.self).avatarColor,'#f17a48');c=await (await api('join',{name:'Gamma',room:'HTTP'},'u3')).json();const sync=await api('sync',{...a,seq:1,input:{x:0,z:0}},'u1');assert.equal(sync.status,200);assert.equal((await sync.json()).snapshot.players.length,3);assert.equal((await api('sync',{session:a.session,token:a.token,seq:2},'u2')).status,401);assert.equal((await api('sync',{session:a.session,token:'f'.repeat(64),seq:2},'u1')).status,401);assert.equal((await api('join',{},null)).status,401);assert.equal((await api('join',{},'u1',{Origin:'https://foreign.test'})).status,403);});
await check('ten and more clients join the same arena without a seat rejection',async()=>{const clients=await Promise.all(Array.from({length:20},async(_,i)=>{const joined=await api('join',{room:'FULL',name:'P'+i,motionVersion:1},'full'+i);assert.equal(joined.status,200);return joined.json();}));await Promise.all(clients.map(async(c,i)=>{const res=await api('sync',{session:c.session,token:c.token,seq:1,afterEvent:c.snapshot.eventCursor,input:{}},'full'+i);assert.equal(res.status,200);assert.equal((await res.json()).snapshot.players.length,20);}));const row=sqlite.prepare('SELECT snapshot FROM arena_rooms WHERE id = ?').get('FULL');assert.equal(Object.keys(JSON.parse(row.snapshot).players).length,20);});
await check('concurrent authenticated syncs advance intermission once and show only connected round members',async()=>{const a=await (await api('join',{room:'ROUND',name:'Same'},'r1')).json(),b=await (await api('join',{room:'ROUND',name:'Same'},'r2')).json(),c=await (await api('join',{room:'ROUND',name:'Stale'},'r3')).json();const store=arenaStore(DB);let roundId;await store.mutate('ROUND',r=>{r.round.status='finished';r.round.results=roomSnapshot(r,a.snapshot.self).leaderboard;r.round.intermissionEndsAt=r.time-1;roundId=r.round.id;r.players[c.snapshot.self].lastSeen=r.time-25000;});const responses=await Promise.all([[a,'r1'],[b,'r2']].map(async([seat,user])=>{const res=await api('sync',{session:seat.session,token:seat.token,seq:1},user);assert.equal(res.status,200);return (await res.json()).snapshot;}));for(const snap of responses){assert.equal(snap.round.id,roundId+1);assert.equal(snap.round.status,'active');assert.equal(snap.leaderboard.length,2);assert.ok(snap.leaderboard.every(p=>p.kills===0&&p.deaths===0));}assert.equal(responses[0].round.startsAt,responses[1].round.startsAt);});
await check('session cap is atomic during concurrent joins',async()=>{const store=arenaStore(DB);const results=await Promise.allSettled(Array.from({length:16},(_,i)=>store.saveSession({id:'cap'+i,tokenHash:'h',principal:'cap',roomId:'CAP1',playerId:'cap'+i})));assert.equal(results.filter(r=>r.status==='fulfilled').length,12);});
await check('server ignores forged positions, damage, scores and stale build commands',async()=>{const packet={session:a.session,token:a.token,seq:2,input:{x:0,z:0,health:999},health:999,kills:99,x:999,command:{id:1,type:'build',mode:'plane'}};const one=await api('sync',packet,'u1');assert.equal(one.status,200);const s=(await one.json()).snapshot,p=s.players.find(p=>p.id===s.self);assert.equal(p.health,100);assert.equal(p.kills,0);assert.ok(p.x<54);assert.equal(p.building.kit.stats.weapon,'none');const again=await api('sync',{...packet,seq:3},'u1');const s2=(await again.json()).snapshot;assert.equal(s2.players.find(p=>p.id===s2.self).building.starts,p.building.starts);});
await check('creation uploads validate geometry and deduplicate retry without another write',async()=>{const packet={session:b.session,token:b.token,seq:1,command:{id:1,type:'build',mode:'generated'},blueprint:dragon};const one=await api('build',packet,'u2');assert.equal(one.status,200);const lootRequest=principal=>new Request('https://brickwild.test/api/arena/blueprint?id=supply%3Arover',{headers:principal?{'oai-authenticated-user-id':principal}:{}});const loot=await handleArenaAPI(lootRequest('u2'),{DB});assert.equal(loot.status,200);assert.deepEqual((await loot.json()).blueprint,SUPPLY_BLUEPRINTS.get('supply:rover'));assert.equal((await handleArenaAPI(lootRequest(null),{DB})).status,401);const before=sqlite.prepare('SELECT COUNT(*) AS n FROM arena_creations').get().n;assert.equal((await api('build',{...packet,seq:2},'u2')).status,200);assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM arena_creations').get().n,before);const bad={...dragon,code:'untrusted'};assert.equal((await api('build',{session:c.session,token:c.token,seq:1,command:{id:1,type:'build',mode:'generated'},blueprint:bad},'u3')).status,400);assert.equal((await api('sync',{padding:'x'.repeat(17000)},'u1')).status,413);});
await check('authenticated HTTP movement stream acknowledges bounded frames and rejects malformed frames',async()=>{
 const response=await api('join',{name:'Stream',room:'MOVE',motionVersion:1},'stream-user'),joined=await response.json(),p=joined.snapshot.players.find(p=>p.id===joined.snapshot.self);assert.equal(p.motion.version,1);
 const packet={session:joined.session,token:joined.token,seq:1,motionEpoch:0,input:{z:1},frames:[[1,0,1,0,0,0]],x:999,z:999};
 const sync=await api('sync',packet,'stream-user');assert.equal(sync.status,200);const moved=(await sync.json()).snapshot.players.find(q=>q.id===p.id);assert.equal(moved.motion.frame,1);assert.ok(Math.abs(moved.z-p.z-p.kit.stats.speed/60)<1e-8);assert.equal(moved.x,p.x);
 assert.equal((await api('sync',{...packet,seq:2,frames:[[2,0,1,0,0,32]]},'stream-user')).status,400);
 assert.equal((await api('sync',{...packet,seq:3,frames:Array.from({length:91},(_,i)=>[i+1,0,1,0,0,0])},'stream-user')).status,400);
 await api('leave',{session:joined.session,token:joined.token},'stream-user');
});
await check('expired room seats give a terminal rejoin error and leave removes membership',async()=>{const store=arenaStore(DB);await store.mutate('HTTP',r=>{if(r.players[c.snapshot.self])r.players[c.snapshot.self].lastSeen=0;advanceRoom(r,r.time+1);});const expired=await api('sync',{session:c.session,token:c.token,seq:1},'u3');assert.equal(expired.status,410);assert.equal((await api('leave',{session:b.session,token:b.token},'u2')).status,200);assert.equal(sqlite.prepare('SELECT id FROM arena_sessions WHERE id = ?').get(b.session),undefined);});
sqlite.close();
console.log(`\n${count} arena checks passed: pure simulation and actual SQLite-backed API checks. No browser, device or production-network performance claim.`);
