import assert from 'node:assert/strict';
import {createVoice,recordingType,VOICE_LIMITS as L} from '../public/voice-controller.js';
const flush=async()=>{for(let i=0;i<12;i++)await Promise.resolve();};
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
let groups=0;async function check(name,fn){await fn();console.log('PASS '+name);groups++;}
function fixture(options={}){
 let clock=0,seq=0;const timers=new Map(),heard=[],states=[],offers=[],recorders=[],recognizers=[],uploads=[],streams=[];
 const track=()=>({stops:0,stop(){this.stops++;}});
 const stream=()=>{const t=track(),s={getTracks:()=>[t],getAudioTracks:()=>[t],track:t};streams.push(s);return s;};
 class Recognition{constructor(){if(options.nativeConstruct)throw Error();recognizers.push(this);}start(){if(options.nativeThrow)throw Error();if(!options.startStall)this.onstart();}stop(){this.stopped=true;}abort(){this.aborted=true;}}
 class Recorder{static isTypeSupported(t){return !options.unsupported&&t===(options.mime||'audio/webm;codecs=opus');}constructor(s,o){if(options.constructFail)throw Error();this.stream=s;this.mimeType=o.mimeType;this.state='inactive';recorders.push(this);}start(){if(options.startFail)throw Error();this.state='recording';}stop(){this.state='inactive';this.stops=(this.stops||0)+1;}chunk(n=10,type=this.mimeType){this.ondataavailable?.({data:new Blob([new Uint8Array(n)],{type})});}end(){this.onstop?.();}}
 const platform={Recognition:options.native===false?null:Recognition,MediaRecorder:Recorder,mediaDevices:{getUserMedia(){if(options.permissionFail)return Promise.reject({name:'NotAllowedError'});return options.permission?.promise||Promise.resolve(stream());}},now:()=>clock,setTimeout(fn,ms){const id=++seq;timers.set(id,{fn,at:clock+ms});return id;},clearTimeout(id){timers.delete(id);},fetch(url,init){if(url==='/api/transcription-status')return Promise.resolve(Response.json({configured:true}));uploads.push({url,...init});return options.response?.promise||Promise.resolve(Response.json({text:options.text??'a synthetic toy dragon'}));}};
 const voice=createVoice({onCommand:(...args)=>heard.push(args),onState:(...args)=>{states.push(args);options.onState?.(...args);},onFallback:(...args)=>offers.push(args),platform});
 const tick=async ms=>{const end=clock+ms;while(true){const next=[...timers].filter(([,t])=>t.at<=end).sort((a,b)=>a[1].at-b[1].at)[0];if(!next)break;clock=next[1].at;timers.delete(next[0]);next[1].fn();await flush();}clock=end;await flush();};
 const finish=async()=>{voice.start();recorders.at(-1).chunk();recorders.at(-1).end();await flush();};
 const clean=()=>{assert.equal(timers.size,0,'all attempt timers released');for(const s of streams)assert.ok(s.track.stops>0,'track stopped');for(const r of recorders)assert.equal(r.state,'inactive');};
 return {voice,heard,states,offers,recorders,recognizers,uploads,streams,stream,tick,clean,finish,platform};
}
const result=t=>({results:[Object.assign([{transcript:t}],{isFinal:true})]});
await check('native success submits one final result and preserves a valid result on late error',()=>{for(const error of [false,true]){const f=fixture();f.voice.start();const r=f.recognizers[0];r.onresult(result('a synthetic castle'));assert.equal(f.heard.length,0);if(error)r.onerror({error:'network'});else r.onend();r.onend();r.onerror({error:'network'});assert.equal(f.heard.length,1);assert.equal(f.offers.length,0);f.clean();}});
await check('missing native and service/no-speech/permission errors offer deliberate recording without upload',()=>{for(const code of ['missing','network','service-not-allowed','not-allowed','audio-capture','no-speech']){const f=fixture({native:code!=='missing'});f.voice.start();if(code!=='missing'){f.recognizers[0].onerror({error:code});f.recognizers[0].onend();}assert.equal(f.offers.length,1);f.voice.start();assert.equal(f.recognizers.length,code==='missing'?0:1,'no native restart each attempt');assert.equal(f.uploads.length,0);assert.equal(f.heard.length,0);f.clean();}});
await check('native constructor/start failure and startup/stop stalls are bounded',async()=>{for(const kind of ['nativeConstruct','nativeThrow','startStall','stopStall']){const f=fixture({[kind]:true});f.voice.start();if(kind==='startStall')await f.tick(L.startMs);if(kind==='stopStall'){f.voice.start();await f.tick(L.stopMs);}assert.equal(f.offers.length,1);f.clean();}const f=fixture();f.voice.start();f.recognizers[0].onresult(result('a synthetic boat'));f.voice.start();await f.tick(L.stopMs);assert.equal(f.heard.length,1);f.clean();});
await check('native duration limit, invalid final and canceled callbacks never duplicate',async()=>{const f=fixture();f.voice.start();await f.tick(L.recordMs+L.stopMs);assert.equal(f.heard.length,0);f.clean();for(const text of ['', 'x','a'.repeat(361)]){const g=fixture();g.voice.start();g.recognizers[0].onresult(result(text));g.recognizers[0].onend();assert.equal(g.heard.length,0);g.clean();}});
await check('WebM and MP4 recording capture final chunk before a single upload and dispatch',async()=>{for(const mime of ['audio/webm;codecs=opus','audio/mp4']){const f=fixture({native:false,mime});f.voice.start();assert.equal(f.uploads.length,0);await f.voice.record();const r=f.recorders[0];r.chunk(12);f.voice.start();assert.equal(f.uploads.length,0);r.chunk(7);const end=r.onstop;end();end();r.chunk(5);await flush();assert.equal(f.uploads.length,1);assert.equal(f.uploads[0].body.size,19);assert.equal(f.uploads[0].body.type,mime);assert.equal(f.uploads[0].credentials,'same-origin');assert.equal(f.heard.length,1);assert.ok(f.states.some(([s])=>s==='ready'));f.clean();}});
await check('unsupported MIME, recorder constructor/start/error, denied permission and device loss release resources',async()=>{for(const kind of ['unsupported','constructFail','startFail','permissionFail','deviceLoss','muted','recorderError']){const f=fixture({[kind]:true});await f.voice.record();if(kind==='deviceLoss')f.streams[0].track.onended();if(kind==='muted')f.streams[0].track.onmute();if(kind==='recorderError')f.recorders[0].onerror();assert.equal(f.heard.length,0);assert.equal(f.uploads.length,0);assert.equal(f.offers.length,1);f.clean();}assert.equal(recordingType({isTypeSupported(){throw Error();}}),null);});
await check('byte overflow, empty audio, wrong final MIME, mixed container and unexpected stop cannot upload',async()=>{for(const kind of ['large','empty','format','mixed','unexpected']){const f=fixture();await f.voice.record();const r=f.recorders[0];if(kind==='large')r.chunk(L.bytes+1);if(kind==='format')r.chunk(10,'audio/ogg');if(kind==='mixed'){r.chunk(10,'audio/webm');r.chunk(10,'audio/mp4');}if(kind==='unexpected')r.end();if(kind==='empty'){f.voice.start();r.end();}await flush();assert.equal(f.uploads.length,0);assert.equal(f.heard.length,0);f.clean();}});
await check('30 second bound stops capture; stopping stall discards instead of sending incomplete audio',async()=>{const f=fixture();await f.voice.record();f.recorders[0].chunk();await f.tick(L.recordMs);assert.equal(f.recorders[0].state,'inactive');assert.ok(f.streams[0].track.stops);assert.equal(f.voice.state,'stopping');await f.tick(L.stopMs);assert.equal(f.uploads.length,0);f.clean();const g=fixture();await g.voice.record();g.recorders[0].chunk();await g.tick(L.recordMs);g.recorders[0].end();await flush();assert.equal(g.heard.length,1);g.clean();});
await check('cancel during permission and permission stall stop late streams before a recorder starts',async()=>{for(const timeout of [false,true]){const permission=deferred(),f=fixture({permission});const pending=f.voice.record();await flush();if(timeout)await f.tick(L.permissionMs);else f.voice.stop();permission.resolve(f.stream());await pending;assert.equal(f.recorders.length,0);assert.equal(f.heard.length,0);f.clean();}});
await check('cancel during capture/stopping ignores retained old recorder events',async()=>{for(const stopping of [false,true]){const f=fixture();await f.voice.record();const r=f.recorders[0],end=r.onstop,data=r.ondataavailable;r.chunk();if(stopping)f.voice.start();f.voice.stop();data({data:new Blob(['synthetic'])});end();await flush();assert.equal(f.uploads.length,0);f.clean();}});
await check('cancel during upload aborts fetch and late response cannot generate',async()=>{const response=deferred(),f=fixture({response});await f.voice.record();await f.finish();assert.equal(f.uploads.length,1);f.voice.stop();assert.ok(f.uploads[0].signal.aborted);response.resolve(Response.json({text:'a synthetic late toy'}));await flush();assert.equal(f.heard.length,0);f.clean();});
await check('cancel after response but before JSON completion and newer attempt defeat old results',async()=>{const response=deferred(),json=deferred(),f=fixture({response});await f.voice.record();await f.finish();response.resolve({ok:true,json:()=>json.promise});await flush();f.voice.stop();await f.voice.record();json.resolve({text:'old synthetic idea'});await flush();assert.equal(f.heard.length,0);f.voice.stop();f.clean();});
await check('transcription timeout, invalid/overlong response and errors do not automatically retry',async()=>{const response=deferred(),f=fixture({response});await f.voice.record();await f.finish();await f.tick(L.transcribeMs);assert.ok(f.uploads[0].signal.aborted);assert.equal(f.uploads.length,1);f.clean();for(const text of ['','a'.repeat(361),null,42]){const g=fixture({response:{promise:Promise.resolve(Response.json({text}))}});await g.voice.record();await g.finish();assert.equal(g.heard.length,0);g.clean();}const g=fixture({response:{promise:Promise.reject(Error('synthetic'))}});await g.voice.record();await g.finish();assert.equal(g.uploads.length,1);assert.equal(g.heard.length,0);g.clean();});
await check('double Record, rapid toggles and native versus recorded race create at most once',async()=>{const permission=deferred(),f=fixture({permission});const p=f.voice.record();await flush();f.voice.record();f.voice.start();permission.resolve(f.stream());await p;assert.equal(f.recorders.length,0);f.clean();const g=fixture();g.voice.start();const r=g.recognizers[0];g.voice.stop();await g.voice.record();r.onresult(result('stale native idea'));r.onend();await g.finish();assert.equal(g.heard.length,1);assert.match(g.heard[0][0],/dragon/);g.clean();});
await check('cancel on ready and pagehide remove all work without a generation',async()=>{let voice;const f=fixture({onState:s=>{if(s==='ready')voice.stop();}});voice=f.voice;await voice.record();await f.finish();assert.equal(f.heard.length,0);f.clean();const events=new Map();globalThis.window={addEventListener:(k,f)=>events.set(k,f),removeEventListener:k=>events.delete(k)};try{const g=fixture();await g.voice.record();events.get('pagehide')();g.clean();assert.equal(g.heard.length,0);g.voice.dispose();assert.equal(events.size,0);}finally{delete globalThis.window;}});
console.log(`${groups} voice lifecycle groups passed; synthetic browser/recorder/fetch only, no microphone or paid calls.`);
