import assert from 'node:assert/strict';
import {newRoom,addPlayer,removePlayer,applyInput,advanceRoom,roomSnapshot,makeKit,hurt,ROUND_MS,INTERMISSION_MS} from '../public/arena-core.js';
import {newMotion,packFrame} from '../public/movement-stream.js';
let checks=0;function check(name,fn){fn();
console.log('PASS '+name);checks++;}
function fixture(){const r=newRoom(100000),p=addPlayer(r,'a','Alpha'),q=addPlayer(r,'b','Beta');p.motion=newMotion(r.time);q.motion=newMotion(r.time);return {r,p,q};}
function end(r){for(const p of Object.values(r.players))p.lastSeen=r.round.endsAt;advanceRoom(r,r.round.endsAt);}
const restart=(r)=>{const at=r.round.intermissionEndsAt;for(const p of Object.values(r.players))p.lastSeen=at;advanceRoom(r,at);};
check('first join starts one five-minute deadline; later joins and snapshots share it',()=>{const r=newRoom(0);advanceRoom(r,90000);addPlayer(r,'a','A',r.time);assert.equal(r.round.endsAt,90000+ROUND_MS);advanceRoom(r,90001);addPlayer(r,'b','B',r.time);assert.equal(roomSnapshot(r,'a').round.endsAt,roomSnapshot(r,'b').round.endsAt);assert.equal(r.round.startsAt,90000);});
check('exact deadline freezes only connected round participants and stops combat',()=>{const {r,p,q}=fixture();p.kills=3;q.kills=1;q.deaths=2;removePlayer(r,q.id);p.lastSeen=r.round.endsAt;advanceRoom(r,r.round.endsAt-1);assert.equal(r.round.status,'active');advanceRoom(r,r.round.endsAt);assert.equal(r.round.status,'finished');assert.deepEqual(r.round.results.map(p=>[p.id,p.kills,p.deaths]),[['a',3,0]]);const result=structuredClone(r.round.results),health=p.health;assert.equal(hurt(r,p,100,'b'),false);applyInput(r,p.id,{seq:1,input:{fire:true,z:1},command:{id:1,type:'fire'}},r.time);advanceRoom(r,r.time+6000);assert.deepEqual(r.round.results,result);assert.equal(p.health,health);assert.equal(r.projectiles.length,0);});
check('automatic intermission retains seats, avatars and loadouts and resets scores exactly once',()=>{const {r,p,q}=fixture();p.kit=makeKit('bow');p.avatarColor='#76b9ff';p.kills=2;q.deaths=2;end(r);const previous=structuredClone(r.round.results);restart(r,p);assert.equal(r.round.id,2);assert.equal(r.round.endsAt,r.time+ROUND_MS);assert.equal(p.kills,0);assert.equal(q.deaths,0);assert.equal(p.kit.id,'bow');assert.equal(p.avatarColor,'#76b9ff');assert.equal(Object.keys(r.players).length,2);assert.equal(r.round.previousResults,undefined);const starts=r.round.startsAt;applyInput(r,q.id,{seq:1,roundId:1,command:{id:1,type:'restart',roundId:1}},r.time);advanceRoom(r,r.time);assert.equal(r.round.id,2);assert.equal(r.round.startsAt,starts);assert.equal(r.events.filter(e=>e.type==='round-started').length,1);});
check('old movement, fire and restart retries cannot affect the next round',()=>{const {r,p}=fixture();end(r);const oldSerial=p.spawnSerial||0;restart(r,p);const before=[p.x,p.y,p.z];applyInput(r,p.id,{seq:2,roundId:1,motionEpoch:oldSerial,frames:[packFrame(1,{z:1})],input:{fire:true},command:{id:2,type:'fire'}},r.time);assert.deepEqual([p.x,p.y,p.z],before);assert.equal(r.projectiles.length,0);});
check('intermission survives reconnect, excludes late spectators, and includes them in the next round',()=>{const {r}=fixture();end(r);const restored=JSON.parse(JSON.stringify(r));advanceRoom(restored,restored.time+5000);addPlayer(restored,'c','Late join',restored.time);assert.equal(roomSnapshot(restored,'c').round.status,'finished');assert.deepEqual(roomSnapshot(restored,'c').leaderboard,r.round.results);assert.equal(restored.players.c.roundId,null);restart(restored,restored.players.c);assert.equal(restored.round.id,2);const legacy=newRoom(50);delete legacy.round;addPlayer(legacy,'l','Legacy');advanceRoom(legacy,51);assert.equal(legacy.round.endsAt,50+ROUND_MS);});
check('thirty-second boundary waits fully; stale sessions expire even during intermission; duplicate names remain distinct',()=>{const {r,p,q}=fixture();p.name=q.name='Builder';end(r);assert.equal(r.round.intermissionEndsAt,r.round.endsAt+INTERMISSION_MS);p.lastSeen=q.lastSeen=r.round.intermissionEndsAt;advanceRoom(r,r.round.intermissionEndsAt-1);assert.equal(r.round.status,'finished');assert.equal(roomSnapshot(r,p.id).leaderboard.length,2);const deadline=r.round.intermissionEndsAt;advanceRoom(r,deadline);assert.equal(r.round.id,2);assert.equal(r.round.startsAt,deadline);advanceRoom(r,deadline);assert.equal(r.round.id,2);q.lastSeen=deadline-21000;advanceRoom(r,deadline+1);assert.equal(roomSnapshot(r,p.id).leaderboard.length,1);});
console.log(`\n${checks} authoritative round checks passed.`);
