import {gameCamera} from '../public/game-camera.js';
import assert from 'node:assert/strict';
import {moveDirect,startJump,JUMP_HEIGHT} from '../public/movement.js';
import {canFit,slideMove,movementShape} from '../public/movement-blocking.js';
import {newRoom,addPlayer,makeKit,predictPlayer,applyInput,advanceRoom} from '../public/arena-core.js';
import {WORLD_ENTITIES,SPAWNS} from '../public/world-data.js';
let checks=0;const check=(name,fn)=>{fn();console.log('PASS '+name);checks++;};
const shape={radius:.45,height:2.5},crate={x:0,y:.7,z:0,w:2,h:1.4,d:2};
function tick(p,input={},boxes=[crate],n=1){for(let i=0;i<n;i++)moveDirect(p,input,1/60,{speed:5,shape,boxes});}
check('higher jump lands on a low prop, stands, walks across, jumps again and falls off its edge',()=>{const p={x:0,y:0,z:-2,yaw:0};tick(p);assert.equal(startJump(p),true);let max=0;for(let i=0;i<18;i++){tick(p,{z:1});max=Math.max(max,p.y);}tick(p,{},[crate],70);assert.equal(p.y,1.4);assert.equal(p.grounded,true);const z=p.z;tick(p,{x:1},[crate],5);assert.ok(p.x<0);assert.equal(p.y,1.4);assert.equal(startJump(p),true);for(let i=0;i<70;i++){tick(p);max=Math.max(max,p.y);}assert.ok(max>3.3&&max<=1.4+JUMP_HEIGHT+.001);assert.equal(p.y,1.4);tick(p,{z:1},[crate],80);assert.ok(p.z>z+4);assert.equal(p.y,0);assert.equal(p.grounded,true);});
check('jump height is bounded, airborne repeat is refused, ceilings stop ascent and destroy support causes falling',()=>{const p={x:0,y:0,z:0};tick(p,{},[]);startJump(p);assert.equal(startJump(p),false);let max=0;for(let i=0;i<80;i++){tick(p,{},[]);max=Math.max(max,p.y);}assert.ok(max>1.9&&max<=2.001);const roof={x:0,y:3,z:0,w:4,h:.4,d:4};startJump(p);for(let i=0;i<80;i++){tick(p,{},[roof]);assert.ok(p.y+shape.height<=2.8001);}assert.equal(p.y,0);Object.assign(p,{y:1.4,vy:0,grounded:true});tick(p);assert.equal(p.y,1.4);tick(p,{},[],60);assert.equal(p.y,0);});
check('all prebuilt props block at their actual height; gates and gaps remain passable',()=>{for(const e of WORLD_ENTITIES){for(const b of e.boxes){const y=Math.max(0,b.y-b.h/2+.001),c=Math.cos(b.yaw||0),sn=Math.sin(b.yaw||0),d=b.w/2+shape.radius+1,start={x:b.x-d*c,y,z:b.z+d*sn},end=slideMove(start,{x:b.x+d*c,y,z:b.z-d*sn},shape,[b]);assert.ok((end.x-b.x)*c-(end.z-b.z)*sn<0,e.id);assert.ok(canFit(end,shape,[b]),e.id);const top=b.y+b.h/2;assert.ok(Math.abs(slideMove({...start,y:top},{x:b.x,y:top,z:b.z},shape,[b]).x-b.x)<1e-8);}}const gate=WORLD_ENTITIES.find(e=>e.id==='gate:0');const center=gate.boxes.at(-1);const pass=slideMove({x:center.x,y:0,z:center.z-4},{x:center.x,y:0,z:center.z+4},shape,gate.boxes);assert.equal(pass.z,center.z+4);});
check('shared prediction and server agree through a jump and solid prop landing',()=>{const r=newRoom(1e5),p=addPlayer(r,'p','Jumper');for(const e of WORLD_ENTITIES)r.destroyed[e.id]=1e12;r.placed=[{...crate,id:'placed:crate',hp:100}];Object.assign(p,{x:0,y:0,z:-2,kit:makeKit('foot')});const q=structuredClone(p);for(let i=0;i<100;i++){const input={jump:i===0,z:i<18?1:0};predictPlayer(q,input,1/60,r);applyInput(r,p.id,{seq:i+1,input},r.time);advanceRoom(r,r.time+1000/60);for(const k of ['x','y','z'])assert.ok(Math.abs(p[k]-q[k])<1e-6,k);}assert.equal(p.y,1.4);});
check('all offered spawns avoid solid prebuilt objects and restored cover waits for occupied space',()=>{const r=newRoom(1e5),p=addPlayer(r,'p','P'),boxes=WORLD_ENTITIES.flatMap(e=>e.boxes);assert.ok(canFit(p,movementShape(p.kit.stats),boxes));const tree=WORLD_ENTITIES.find(e=>e.id==='tree:inner:0');Object.assign(p,{x:tree.boxes[0].x,y:0,z:tree.boxes[0].z});r.destroyed[tree.id]=r.time;advanceRoom(r,r.time+10);assert.ok(r.destroyed[tree.id]>r.time);});
check('Practice and Arena share framing and full sky look for the same character or mount',()=>{for(const mode of ['foot','bow','car','plane']){const kit=makeKit(mode),p={x:5,y:0,z:3,mode,yaw:1};for(const pitch of [-.75,.46,.92]){const look={yaw:2,pitch},practice=gameCamera({...p,arena:false},kit,look,16/9),arena=gameCamera({...p,arena:true},kit,look,16/9);assert.deepEqual(practice,arena);assert.equal(p.yaw,1);if(pitch<0)assert.ok(practice.target.y>practice.position.y+5);}}});
console.log(`\n${checks} support and solid-map checks passed.`);
